{
 "title": "BEAM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(erlang_vm_process_count, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{instance=\"$node\"}[$interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Reductions"
    },
    {
     "expr": "irate(erlang_vm_statistics_runtime_milliseconds{instance=\"$node\"}[$interval])",
     "legendFormat": "Runtime"
    },
    {
     "expr": "system_load{instance=\"$node\"}/256",
     "legendFormat": "Load average (5)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$node\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"system\"}",
     "legendFormat": "System memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"ets\"}",
     "legendFormat": "ETS"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory breakdown",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(erlang_vm_allocators{usage=\"carriers_size\", instance=~\"$node\"}) by (alloc)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg by (method) (rate(cowboy_request_duration_seconds_sum[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests rates (per minute)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (method, status_class) (rate(cowboy_requests_total[5m])) * 60\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "VM GC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\"}[$interval])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "File Descriptors & Ports",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$node\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{instance=\"$node\"}",
     "legendFormat": "Max FDs"
    },
    {
     "expr": "erlang_vm_port_limit{instance=\"$node\"}",
     "legendFormat": "Max Ports"
    },
    {
     "expr": "erlang_vm_port_count{instance=\"$node\"}",
     "legendFormat": "Ports"
    }
   ]
  }
 ]
}