#!/usr/bin/env bash
# sb-setup.sh -- generate LapEE operator Secure Boot keys, sign the
# UKI, produce UEFI-enrolment artefacts.
#
# Secure Boot in v1.2.1 is operator-provisioned. Each operator:
#   1. Runs `sb-setup.sh keys' ONCE to generate a fresh PK/KEK/db set
#      per their machine. Keys live under `secureboot/', which is
#      .gitignored -- keys never leave the operator's host.
#   2. Runs `sb-setup.sh sign' after every `make hb-usb-image' to
#      sign the produced UKI with db.key.
#   3. Runs `sb-setup.sh enrol' once per Framework to produce the
#      .auth files that go on a separate FAT-formatted USB stick the
#      Framework reads during Secure Boot setup-mode enrolment.
#
# After enrolment, Secure Boot ON in the Framework BIOS will accept
# the signed UKI and reject anything else.
#
# Rationale (vs. signing with Microsoft shim): shim is a generic
# bootloader and bundles MOK which defeats the single-purpose
# attestation premise. LapEE's operator-owned key means the chain of
# trust terminates at a key the operator physically controls --
# matches the paper's "device identity anchored at the TPM vendor
# root via the EK certificate chain, operator-owned UEFI trust
# anchor via PK/KEK/db" statement.
#
# Required tools:
#   - openssl   (keys + self-sign certs)
#   - sbsign    (sbsigntool package; signs PE+COFF binaries)
#   - sbsigntool's efi-updatevar / cert-to-efi-sig-list / sign-efi-sig-list
#
# On macOS: `brew install sbsigntool` then `brew install gnu-efi'
# for efi-updatevar. On Linux: `apt install sbsigntool efitools'.

set -euo pipefail

cd "$(dirname "$0")/.."
LAPEE=$(pwd)
SB_DIR="$LAPEE/secureboot"
BUILD_UKI="$LAPEE/work/usb-build/BootX64.efi"
SIGNED_UKI="$LAPEE/work/usb-build/BootX64.signed.efi"

usage() {
    cat <<USAGE
usage: sb-setup.sh <command>

Commands:
  keys         Generate operator PK/KEK/db keys under $SB_DIR.
               Run ONCE per operator. Keys never leave the host.

  sign         Sign the UKI at $BUILD_UKI using db.key. Writes
               $SIGNED_UKI; a separate step copies it over the
               unsigned UKI into the USB image.

  enrol        Produce UEFI enrolment .auth files in $SB_DIR/enrol/.
               Copy those to a separate FAT-formatted USB stick;
               plug that stick into the Framework, enter Secure Boot
               setup mode, and use the BIOS "enrol db/KEK/PK" UI
               (F2 -> Security -> Secure Boot).

  check        Print the state of everything. Keys exist? UKI signed?
                Enrolment artefacts ready?

  tools        Print what's installed and what's missing.

USAGE
    exit 1
}

cmd="${1:-}"
[ -n "$cmd" ] || usage

case "$cmd" in
    tools|check|keys|sign|enrol) ;;
    *) usage ;;
esac

have_tool() { command -v "$1" >/dev/null 2>&1; }

if [ "$cmd" = "tools" ]; then
    echo "=== SB signing tools on this host ==="
    for t in openssl sbsign sbverify cert-to-efi-sig-list \
             sign-efi-sig-list efi-updatevar uuidgen; do
        if have_tool "$t"; then
            printf "  [ok]  %s -> %s\n" "$t" "$(command -v "$t")"
        else
            printf "  [MISSING] %s\n" "$t"
        fi
    done
    cat <<'NOTE'

If tools are missing:
  macOS: brew install sbsigntool
         brew install efitools     # for cert-to-efi-sig-list etc.
  Linux: apt install sbsigntool efitools

Keys are generated by openssl (always available). The missing tools
matter for `sign' (needs sbsign) and `enrol' (needs efitools).
NOTE
    exit 0
fi

if [ "$cmd" = "check" ]; then
    echo "=== SB state ==="
    printf "  secureboot dir:     "
    [ -d "$SB_DIR" ] && echo "$SB_DIR" || echo "MISSING (run: $0 keys)"
    for name in PK KEK db; do
        if [ -f "$SB_DIR/$name.key" ] && [ -f "$SB_DIR/$name.crt" ]; then
            subj=$(openssl x509 -in "$SB_DIR/$name.crt" -noout -subject \
                    2>/dev/null | sed 's/^subject=//')
            printf "  %-18s %s\n" "$name keys:" "$subj"
        else
            printf "  %-18s MISSING\n" "$name keys:"
        fi
    done
    printf "  unsigned UKI:       "
    [ -f "$BUILD_UKI" ] && echo "$BUILD_UKI ($(stat -f %z "$BUILD_UKI") bytes)" \
        || echo "MISSING (run: make hb-usb-image)"
    printf "  signed UKI:         "
    [ -f "$SIGNED_UKI" ] && echo "$SIGNED_UKI ($(stat -f %z "$SIGNED_UKI") bytes)" \
        || echo "MISSING (run: $0 sign)"
    for name in PK KEK db; do
        f="$SB_DIR/enrol/$name.auth"
        printf "  enrol/%s.auth:      " "$name"
        [ -f "$f" ] && echo "$f ($(stat -f %z "$f") bytes)" \
            || echo "MISSING (run: $0 enrol)"
    done
    exit 0
fi

if [ "$cmd" = "keys" ]; then
    mkdir -p "$SB_DIR"
    chmod 700 "$SB_DIR"
    gen() {
        local name="$1" cn="$2"
        if [ -f "$SB_DIR/$name.key" ] && [ -f "$SB_DIR/$name.crt" ]; then
            echo "  [skip] $name: already exists at $SB_DIR/$name.{key,crt}"
            return
        fi
        echo "  [gen] $name ($cn)"
        openssl req -new -x509 -newkey rsa:2048 -sha256 -nodes \
                -subj "/CN=$cn/" -days 3650 \
                -keyout "$SB_DIR/$name.key" \
                -out    "$SB_DIR/$name.crt" 2>/dev/null
        chmod 600 "$SB_DIR/$name.key"
    }
    echo "=== generating operator Secure Boot keys in $SB_DIR ==="
    gen PK  "LapEE operator Platform Key ($(hostname))"
    gen KEK "LapEE operator Key Exchange Key ($(hostname))"
    gen db  "LapEE operator db signing key ($(hostname))"
    echo ""
    echo "Keys are operator-owned. Keep $SB_DIR/*.key files private."
    echo "Commit ONLY the .crt files if you want key rotation to be"
    echo "auditable; the .key files must never leave this host."
    exit 0
fi

if [ "$cmd" = "sign" ]; then
    have_tool sbsign || {
        echo "[fail] sbsign not found. Install: brew install sbsigntool"; exit 2;
    }
    [ -f "$SB_DIR/db.key" ] || { echo "[fail] run $0 keys first"; exit 2; }
    [ -f "$BUILD_UKI" ] || { echo "[fail] UKI not found at $BUILD_UKI"; exit 2; }
    echo "=== signing UKI with db.key ==="
    sbsign --key "$SB_DIR/db.key" --cert "$SB_DIR/db.crt" \
           --output "$SIGNED_UKI" "$BUILD_UKI"
    ls -la "$SIGNED_UKI"
    if have_tool sbverify; then
        echo "--- sbverify with db.crt ---"
        sbverify --cert "$SB_DIR/db.crt" "$SIGNED_UKI"
    fi
    echo ""
    echo "To make the signed UKI the one on the USB image, overwrite"
    echo "the unsigned version and re-write the USB stick:"
    echo "    cp '$SIGNED_UKI' '$BUILD_UKI'"
    echo "    make hb-usb-image     # re-wraps UKI into the .img"
    echo "    make hb-usb-write DEV=/dev/diskN"
    exit 0
fi

if [ "$cmd" = "enrol" ]; then
    have_tool cert-to-efi-sig-list && have_tool sign-efi-sig-list || {
        echo "[fail] efitools not found. Install: brew install efitools"
        exit 2
    }
    [ -f "$SB_DIR/PK.key" ] || { echo "[fail] run $0 keys first"; exit 2; }

    # Use a stable GUID per operator for the enrolment; re-enrolment
    # on the same Framework stays idempotent instead of stacking
    # multiple PKs.
    if [ ! -f "$SB_DIR/GUID.txt" ]; then
        uuidgen > "$SB_DIR/GUID.txt"
    fi
    GUID=$(cat "$SB_DIR/GUID.txt")
    mkdir -p "$SB_DIR/enrol"

    echo "=== producing UEFI enrolment .auth files ==="
    echo "    GUID: $GUID"
    cd "$SB_DIR"
    # PK (top of the chain, self-signed with the PK key itself).
    cert-to-efi-sig-list -g "$GUID" PK.crt PK.esl
    sign-efi-sig-list -k PK.key -c PK.crt PK PK.esl enrol/PK.auth
    # KEK (chains under PK).
    cert-to-efi-sig-list -g "$GUID" KEK.crt KEK.esl
    sign-efi-sig-list -k PK.key -c PK.crt KEK KEK.esl enrol/KEK.auth
    # db (chains under KEK).
    cert-to-efi-sig-list -g "$GUID" db.crt db.esl
    sign-efi-sig-list -k KEK.key -c KEK.crt db db.esl enrol/db.auth
    rm -f PK.esl KEK.esl db.esl
    cd "$LAPEE"
    ls -la "$SB_DIR/enrol/"
    cat <<'ENROL'

Enrolment procedure on the Framework 13:
  1. Copy the three .auth files above to a separate FAT-formatted
     USB stick (not the LapEE boot stick). Root-level is fine.
  2. Plug the enrolment USB into the Framework.
  3. Power on, F2 to enter BIOS.
  4. Security -> Secure Boot -> Enter Setup Mode (clears factory
     Microsoft keys; takes the machine out of a trust-chain rooted
     at Redmond and into one rooted at your operator key).
  5. Still in Security -> Secure Boot, enrol the three files in
     order: db.auth, KEK.auth, PK.auth. (PK last; enrolling PK
     exits setup mode and re-enables Secure Boot on the operator
     chain.)
  6. Save + exit. Boot from the LapEE USB -- the signed UKI from
     `sb-setup.sh sign' will pass SB verification; any other UEFI
     binary (including the factory Microsoft-signed installer
     media) will be rejected. This is the intended single-purpose
     appliance posture.

To revert to factory Microsoft keys: Security -> Secure Boot ->
Restore Factory Keys.
ENROL
    exit 0
fi
