name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/hyperbeam:latest
            ghcr.io/${{ github.repository_owner }}/hyperbeam:${{ github.sha }}
